### ISSUE TITLE
Errors causing app to crash

### ISSUE THREAD

**Issue by Logan9312** [CMPUT301W24T30/ScanPal#59]
# Issue
I am not sure if all of these errors are related, but the Chimera one for sure is causing issues, we need to look into what's causing them and fix it so our app can run properly.

![Image](https://github.com/CMPUT301W24T30/ScanPal/assets/87048158/43746f5b-2fa3-4377-adca-38eba9620805)
![Image](https://github.com/CMPUT301W24T30/ScanPal/assets/87048158/a030fc90-0134-4bd0-816e-76538554423a)
![Image](https://github.com/CMPUT301W24T30/ScanPal/assets/87048158/26f0b608-e8be-46f5-8d09-a0688631a08a)
![Image](https://github.com/CMPUT301W24T30/ScanPal/assets/87048158/2bdd0ccc-ad04-4d17-b7cb-ca527f25e717)
![Image](https://github.com/CMPUT301W24T30/ScanPal/assets/87048158/071888de-00c4-40a1-b58d-2e8bdf4238f1)

# How To Replicate
Launch the app and try signing in as a new user

# Full Logs below

<details><summary>Details</summary>
<p>

```java
2024-03-05 10:55:15.550  8535-8535  example.scanpal         com.example.scanpal                  I  Late-enabling -Xcheck:jni
2024-03-05 10:55:15.649  8535-8535  example.scanpal         com.example.scanpal                  I  Using CollectorTypeCC GC.
2024-03-05 10:55:15.656  8535-8535  example.scanpal         com.example.scanpal                  W  Unexpected CPU variant for x86: x86_64.
                                                                                                    Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default
2024-03-05 10:55:15.885  8535-8535  re-initialized>         com.example.scanpal                  W  type=1400 audit(0.0:472): avc:  granted  { execute } for  path="/data/data/com.example.scanpal/code_cache/startup_agents/13682499-agent.so" dev="dm-39" ino=320973 scontext=u:r:untrusted_app:s0:c182,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c182,c256,c512,c768 tclass=file app=com.example.scanpal
2024-03-05 10:55:15.901  8535-8535  example.scanpal         com.example.scanpal                  W  DexFile /data/data/com.example.scanpal/code_cache/.studio/instruments-23bb1108.jar is in boot class path but is not in a known location
2024-03-05 10:55:15.922  8535-8535  example.scanpal         com.example.scanpal                  W  Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2024-03-05 10:55:15.927  8535-8535  example.scanpal         com.example.scanpal                  W  Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2024-03-05 10:55:15.931  8535-8535  example.scanpal         com.example.scanpal                  W  Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
2024-03-05 10:55:15.931  8535-8535  example.scanpal         com.example.scanpal                  W  Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
2024-03-05 10:55:15.939  8535-8535  example.scanpal         com.example.scanpal                  W  Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2024-03-05 10:55:15.953  8535-8535  example.scanpal         com.example.scanpal                  W  Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2024-03-05 10:55:15.961  8535-8535  example.scanpal         com.example.scanpal                  W  Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
2024-03-05 10:55:15.970  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 171979766; UID 10182; state: ENABLED
2024-03-05 10:55:15.970  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 242716250; UID 10182; state: ENABLED
2024-03-05 10:55:16.009  8535-8535  nativeloader            com.example.scanpal                  D  Configuring clns-6 for other apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~wHAfV6cKOs0DeoPzweZW9g==/com.example.scanpal-IbYe2fVdxeBidNuZZFvw6w==/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.example.scanpal
2024-03-05 10:55:16.010  8535-8535  ApplicationLoaders      com.example.scanpal                  D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
2024-03-05 10:55:16.011  8535-8535  ApplicationLoaders      com.example.scanpal                  D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
2024-03-05 10:55:16.014  8535-8535  ziparchive              com.example.scanpal                  W  Unable to open '/data/app/~~wHAfV6cKOs0DeoPzweZW9g==/com.example.scanpal-IbYe2fVdxeBidNuZZFvw6w==/base.dm': No such file or directory
2024-03-05 10:55:16.014  8535-8535  ziparchive              com.example.scanpal                  W  Unable to open '/data/app/~~wHAfV6cKOs0DeoPzweZW9g==/com.example.scanpal-IbYe2fVdxeBidNuZZFvw6w==/base.dm': No such file or directory
2024-03-05 10:55:16.459  8535-8535  nativeloader            com.example.scanpal                  D  Configuring clns-7 for other apk /data/app/~~wHAfV6cKOs0DeoPzweZW9g==/com.example.scanpal-IbYe2fVdxeBidNuZZFvw6w==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~wHAfV6cKOs0DeoPzweZW9g==/com.example.scanpal-IbYe2fVdxeBidNuZZFvw6w==/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.example.scanpal
2024-03-05 10:55:16.507  8535-8535  GraphicsEnvironment     com.example.scanpal                  V  Currently set values for:
2024-03-05 10:55:16.507  8535-8535  GraphicsEnvironment     com.example.scanpal                  V    angle_gl_driver_selection_pkgs=[]
2024-03-05 10:55:16.507  8535-8535  GraphicsEnvironment     com.example.scanpal                  V    angle_gl_driver_selection_values=[]
2024-03-05 10:55:16.508  8535-8535  GraphicsEnvironment     com.example.scanpal                  V  ANGLE GameManagerService for com.example.scanpal: false
2024-03-05 10:55:16.508  8535-8535  GraphicsEnvironment     com.example.scanpal                  V  com.example.scanpal is not listed in per-application setting
2024-03-05 10:55:16.508  8535-8535  GraphicsEnvironment     com.example.scanpal                  V  Neither updatable production driver nor prerelease driver is supported.
2024-03-05 10:55:16.616  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 183155436; UID 10182; state: ENABLED
2024-03-05 10:55:16.695  8535-8535  FirebaseApp             com.example.scanpal                  I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2024-03-05 10:55:16.702  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 3400644; UID 10182; state: ENABLED
2024-03-05 10:55:16.735  8535-8535  FirebaseInitProvider    com.example.scanpal                  I  FirebaseApp initialization successful
2024-03-05 10:55:16.866  8535-8565  libEGL                  com.example.scanpal                  D  loaded /vendor/lib64/egl/libEGL_emulation.so
2024-03-05 10:55:16.904  8535-8565  libEGL                  com.example.scanpal                  D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2024-03-05 10:55:16.919  8535-8565  libEGL                  com.example.scanpal                  D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
2024-03-05 10:55:17.050  8535-8535  AppCompatDelegate       com.example.scanpal                  D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2024-03-05 10:55:17.222  8535-8535  example.scanpal         com.example.scanpal                  W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2024-03-05 10:55:17.222  8535-8535  example.scanpal         com.example.scanpal                  W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2024-03-05 10:55:17.635  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 210923482; UID 10182; state: ENABLED
2024-03-05 10:55:17.819  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 237531167; UID 10182; state: DISABLED
2024-03-05 10:55:17.823  8535-8535  OpenGLRenderer          com.example.scanpal                  W  Unknown dataspace 0
2024-03-05 10:55:17.835  8535-8535  Choreographer           com.example.scanpal                  I  Skipped 60 frames!  The application may be doing too much work on its main thread.
2024-03-05 10:55:17.941  8535-8563  OpenGLRenderer          com.example.scanpal                  W  Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2024-03-05 10:55:17.941  8535-8563  OpenGLRenderer          com.example.scanpal                  W  Failed to initialize 101010-2 format, error = EGL_SUCCESS
2024-03-05 10:55:18.018  8535-8563  Gralloc4                com.example.scanpal                  I  mapper 4.x is not supported
2024-03-05 10:55:18.062  8535-8563  OpenGLRenderer          com.example.scanpal                  E  Unable to match the desired swap behavior.
2024-03-05 10:55:18.158  8535-8552  OpenGLRenderer          com.example.scanpal                  I  Davey! duration=1327ms; Flags=1, FrameTimelineVsyncId=65905, IntendedVsync=435953220400, Vsync=436953220360, InputEventId=0, HandleInputStart=436968508300, AnimationStart=436968700500, PerformTraversalsStart=436969728400, DrawStart=437194878200, FrameDeadline=435969887066, FrameInterval=436967408300, FrameStartTime=16666666, SyncQueued=437218958900, SyncStart=437225371300, IssueDrawCommandsStart=437226323900, SwapBuffers=437280378000, FrameCompleted=437287226200, DequeueBufferDuration=22000, QueueBufferDuration=250100, GpuCompleted=437287226200, SwapBuffersCompleted=437282709900, DisplayPresentTime=0, CommandSubmissionCompleted=437280378000, 
2024-03-05 10:55:21.976  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=535.02ms min=1.71ms max=3648.03ms count=7
2024-03-05 10:55:22.070  8535-8535  Compatibil...geReporter com.example.scanpal                  D  Compat change id reported: 163400105; UID 10182; state: ENABLED
2024-03-05 10:55:22.071  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:e96973aa: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
2024-03-05 10:55:22.072  8535-8535  InputMethodManager      com.example.scanpal                  D  showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{9e44698 VFED..CL. .F.P..ID 110,592-971,705 #7f08004f app:id/addUsername aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
2024-03-05 10:55:22.095  8535-8535  AssistStructure         com.example.scanpal                  I  Flattened final assist data: 2272 bytes, containing 1 windows, 11 views
2024-03-05 10:55:22.385  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:22.430  8535-8595  InteractionJankMonitor  com.example.scanpal                  D  Build configuration failed!
                                                                                                    java.lang.IllegalArgumentException: Must pass in a valid surface control if only instrument surface; 
                                                                                                    	at com.android.internal.jank.InteractionJankMonitor$Configuration.validate(InteractionJankMonitor.java:1259)
                                                                                                    	at com.android.internal.jank.InteractionJankMonitor$Configuration.<init>(InteractionJankMonitor.java:1217)
                                                                                                    	at com.android.internal.jank.InteractionJankMonitor$Configuration.<init>(Unknown Source:0)
                                                                                                    	at com.android.internal.jank.InteractionJankMonitor$Configuration$Builder.build(InteractionJankMonitor.java:1197)
                                                                                                    	at com.android.internal.jank.InteractionJankMonitor.begin(InteractionJankMonitor.java:611)
                                                                                                    	at android.view.inputmethod.ImeTracker$ImeJankTracker.onRequestAnimation(ImeTracker.java:717)
                                                                                                    	at android.view.InsetsController$InternalAnimationControlListener$2.onAnimationStart(InsetsController.java:448)
                                                                                                    	at android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:695)
                                                                                                    	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda0.call(Unknown Source:4)
                                                                                                    	at android.animation.Animator.callOnList(Animator.java:669)
                                                                                                    	at android.animation.Animator.notifyListeners(Animator.java:608)
                                                                                                    	at android.animation.Animator.notifyStartListeners(Animator.java:625)
                                                                                                    	at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1334)
                                                                                                    	at android.animation.ValueAnimator.start(ValueAnimator.java:1149)
                                                                                                    	at android.animation.ValueAnimator.start(ValueAnimator.java:1173)
                                                                                                    	at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java:470)
                                                                                                    	at android.view.InsetsAnimationThreadControlRunner.lambda$new$0(InsetsAnimationThreadControlRunner.java:129)
                                                                                                    	at android.view.InsetsAnimationThreadControlRunner.$r8$lambda$3zGKYd3XPzPnvMO2hiF8a88M6T0(Unknown Source:0)
                                                                                                    	at android.view.InsetsAnimationThreadControlRunner$$ExternalSyntheticLambda2.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-03-05 10:55:22.624  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:e96973aa: onShown
2024-03-05 10:55:23.020  8535-8593  ActivityThread          com.example.scanpal                  E  Failed to find provider info for com.google.android.gms.fonts
2024-03-05 10:55:23.060  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=271.03ms min=21.52ms max=476.84ms count=4
2024-03-05 10:55:23.619  8535-8617  ProfileInstaller        com.example.scanpal                  D  Installing profile for com.example.scanpal
2024-03-05 10:55:24.078  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=508.80ms min=498.92ms max=518.67ms count=2
2024-03-05 10:55:25.575  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=498.66ms min=497.87ms max=499.24ms count=3
2024-03-05 10:55:26.586  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=336.91ms min=51.08ms max=500.30ms count=3
2024-03-05 10:55:27.649  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=117.80ms min=14.66ms max=225.19ms count=9
2024-03-05 10:55:28.495  8535-8535  AssistStructure         com.example.scanpal                  I  Flattened final assist data: 2344 bytes, containing 1 windows, 11 views
2024-03-05 10:55:28.497  8535-8535  WindowOnBackDispatcher  com.example.scanpal                  W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@210734941 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@efaa737
2024-03-05 10:55:28.564  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:28.564  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:ca435239: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-03-05 10:55:28.659  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=91.78ms min=35.28ms max=228.43ms count=11
2024-03-05 10:55:28.676  8535-8535  AssistStructure         com.example.scanpal                  I  Flattened final assist data: 2344 bytes, containing 1 windows, 11 views
2024-03-05 10:55:28.681  8535-8535  WindowOnBackDispatcher  com.example.scanpal                  W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@210734941 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@fc20d
2024-03-05 10:55:28.694  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:28.694  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:593065f4: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-03-05 10:55:30.158  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=499.69ms min=499.14ms max=500.26ms count=3
2024-03-05 10:55:30.377  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:ca19487f: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
2024-03-05 10:55:30.377  8535-8535  InputMethodManager      com.example.scanpal                  D  showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{5448ef1 VFED..CL. .F.P..ID 111,789-969,907 #7f08004b app:id/addFirstName aid=1073741825} flags=0 reason=SHOW_SOFT_INPUT
2024-03-05 10:55:30.390  8535-8535  WindowOnBackDispatcher  com.example.scanpal                  W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@210734941 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@502e710
2024-03-05 10:55:30.397  8535-8535  AssistStructure         com.example.scanpal                  I  Flattened final assist data: 2344 bytes, containing 1 windows, 11 views
2024-03-05 10:55:30.451  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:30.451  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:adfd7c2f: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-03-05 10:55:30.463  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:30.464  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:ca19487f: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-03-05 10:55:30.954  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:19221652: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
2024-03-05 10:55:30.955  8535-8535  InputMethodManager      com.example.scanpal                  D  showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{1247ad6 VFED..CL. .F.P..ID 111,981-969,1099 #7f08004c app:id/addLastName aid=1073741826} flags=0 reason=SHOW_SOFT_INPUT
2024-03-05 10:55:30.976  8535-8535  AssistStructure         com.example.scanpal                  I  Flattened final assist data: 2392 bytes, containing 1 windows, 11 views
2024-03-05 10:55:30.979  8535-8535  RemoteInpu...ectionImpl com.example.scanpal                  W  setComposingRegion on inactive InputConnection
2024-03-05 10:55:30.979  8535-8535  WindowOnBackDispatcher  com.example.scanpal                  W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@210734941 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@98dcc27
2024-03-05 10:55:31.020  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:31.021  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:4f77719d: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-03-05 10:55:31.021  8535-8535  InsetsController        com.example.scanpal                  D  show(ime(), fromIme=true)
2024-03-05 10:55:31.021  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:19221652: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-03-05 10:55:31.167  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=62.48ms min=11.05ms max=143.98ms count=16
2024-03-05 10:55:32.359  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=119.14ms min=35.33ms max=491.91ms count=10
2024-03-05 10:55:32.387  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:f6c52d68: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
2024-03-05 10:55:32.394  8535-8535  WindowOnBackDispatcher  com.example.scanpal                  W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@210734941 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@49b4aed
2024-03-05 10:55:32.643  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:e682456b: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2024-03-05 10:55:32.644  8535-8535  ImeTracker              com.example.scanpal                  I  com.example.scanpal:f6c52d68: onHidden
2024-03-05 10:55:33.384  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=341.61ms min=65.55ms max=488.16ms count=3
2024-03-05 10:55:33.635  8535-8586  DynamiteModule          com.example.scanpal                  W  Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
2024-03-05 10:55:34.425  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=18.85ms min=2.18ms max=200.00ms count=52
2024-03-05 10:55:34.543  8535-8586  ActivityThread          com.example.scanpal                  E  Failed to find provider info for com.google.android.gms.chimera
2024-03-05 10:55:34.543  8535-8586  DynamiteModule          com.example.scanpal                  W  Failed to retrieve remote module version.
2024-03-05 10:55:34.584  8535-8586  nativeloader            com.example.scanpal                  D  Configuring clns-8 for other apk /system/framework/com.android.media.remotedisplay.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/product/priv-app/PrebuiltGmsCore/lib/x86_64:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2024-03-05 10:55:34.586  8535-8586  nativeloader            com.example.scanpal                  D  Configuring clns-9 for other apk /system/framework/com.android.location.provider.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/product/priv-app/PrebuiltGmsCore/lib/x86_64:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2024-03-05 10:55:34.586  8535-8586  ApplicationLoaders      com.example.scanpal                  D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
2024-03-05 10:55:34.586  8535-8586  ApplicationLoaders      com.example.scanpal                  D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
2024-03-05 10:55:34.591  8535-8586  nativeloader            com.example.scanpal                  D  InitLlndkLibrariesProduct: libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libRS.so:libandroid_net.so:libbinder_ndk.so:libc.so:libcgrouprc.so:libclang_rt.asan-x86_64-android.so:libcom.android.tethering.connectivity_native.so:libdl.so:libft2.so:liblog.so:libm.so:libmediandk.so:libnativewindow.so:libneuralnetworks.so:libselinux.so:libsync.so:libvndksupport.so:libvulkan.so
2024-03-05 10:55:34.591  8535-8586  nativeloader            com.example.scanpal                  D  Configuring product-clns-10 for unbundled product apk /product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk. target_sdk_version=33, uses_libraries=, library_path=/product/priv-app/PrebuiltGmsCore/lib/x86_64:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86_64:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms:/product/lib64:/system/product/lib64
2024-03-05 10:55:34.594  8535-8586  nativeloader            com.example.scanpal                  D  InitVndkspLibrariesProduct: android.hardware.common-V2-ndk.so:android.hardware.common.fmq-V1-ndk.so:android.hardware.graphics.allocator-V2-ndk.so:android.hardware.graphics.common-V4-ndk.so:android.hardware.graphics.common@1.0.so:android.hardware.graphics.common@1.1.so:android.hardware.graphics.common@1.2.so:android.hardware.graphics.composer3-V1-ndk.so:android.hardware.graphics.mapper@2.0.so:android.hardware.graphics.mapper@2.1.so:android.hardware.graphics.mapper@3.0.so:android.hardware.graphics.mapper@4.0.so:android.hardware.renderscript@1.0.so:android.hidl.memory.token@1.0.so:android.hidl.memory@1.0-impl.so:android.hidl.memory@1.0.so:android.hidl.safe_union@1.0.so:libRSCpuRef.so:libRSDriver.so:libRS_internal.so:libbase.so:libbcinfo.so:libblas.so:libc++.so:libcompiler_rt.so:libcutils.so:libdmabufheap.so:libgralloctypes.so:libhardware.so:libhidlbase.so:libhidlmemory.so:libion.so:libjsoncpp.so:liblzma.so:libprocessgroup.so:libunwindstack.so:libutils.so:libutilscallstack.so:libz.so
2024-03-05 10:55:35.924  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=498.05ms min=496.35ms max=500.05ms count=3
2024-03-05 10:55:36.924  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=499.97ms min=499.81ms max=500.13ms count=2
2024-03-05 10:55:37.924  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=499.92ms min=498.61ms max=501.23ms count=2
2024-03-05 10:55:38.924  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=500.10ms min=498.35ms max=501.85ms count=2
2024-03-05 10:55:40.442  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=505.78ms min=499.51ms max=517.57ms count=3
2024-03-05 10:55:41.942  8535-8563  EGL_emulation           com.example.scanpal                  D  app_time_stats: avg=27.21ms min=11.63ms max=500.46ms count=55
2024-03-05 10:55:42.723  8535-8586  ActivityThread          com.example.scanpal                  E  Failed to find provider info for com.google.android.gms.chimera
2024-03-05 10:55:42.723  8535-8586  DynamiteModule          com.example.scanpal                  W  Failed to retrieve remote module version.
2024-03-05 10:55:42.723  8535-8586  DynamiteModule          com.example.scanpal                  I  Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
2024-03-05 10:55:42.724  8535-8586  ProviderInstaller       com.example.scanpal                  W  Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
2024-03-05 10:55:42.736  8535-8586  ApplicationLoaders      com.example.scanpal                  D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
2024-03-05 10:55:42.736  8535-8586  ApplicationLoaders      com.example.scanpal                  D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
2024-03-05 10:55:42.762  8535-8586  NativeCrypto            com.example.scanpal                  V  Registering com/google/android/gms/org/conscrypt/NativeCrypto's 295 native methods...
2024-03-05 10:55:42.785  8535-8586  example.scanpal         com.example.scanpal                  W  Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (unsupported, reflection, allowed)
2024-03-05 10:55:42.865  8535-8586  ProviderInstaller       com.example.scanpal                  I  Installed default security provider GmsCore_OpenSSL
2024-03-05 10:55:43.142  8535-8869  TrafficStats            com.example.scanpal                  D  tagSocket(136) with statsTag=0xffffffff, statsUid=-1
2024-03-05 10:55:43.180  8535-8869  example.scanpal         com.example.scanpal                  W  Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
2024-03-05 10:55:43.279  8535-8869  example.scanpal         com.example.scanpal                  W  Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)
---------------------------- PROCESS ENDED (8535) for package com.example.scanpal ----------------------------
2024-03-05 10:55:50.845  8535-8535  ActivityThread          com.example.scanpal                  E  Failed to find provider info for com.google.android.gms.chimera
2024-03-05 10:55:50.845  8535-8535  DynamiteDebugLogger     com.example.scanpal                  W  ContentProvider lookup failed: java.lang.IllegalArgumentException: Unknown authority com.google.android.gms.chimera

``` 

</p>
</details>

**Comment by Nandan-18** [comment]
The issue is not linked with the app, it appears to be an issue with the android emulator/settings/configs.

Working Fix:
1) Find the app in the emulator settings
2) Go to 'Storage & Cache'
3) Clear the app's 'Cache' and 'Storage'
4) Uninstall the app from inside the emulator
5) Close the emulator and reinstall the app
